<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USER-VAIO" name="Test1" tests="2" failures="2" timestamp="6 Oct 2014 05:42:01 GMT" time="12.437" errors="0">
  <testcase name="login" time="0.016" classname="Testngpackage.LoginToActitime">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Testngpackage.LoginToActitime.login(LoginToActitime.java:25)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login1" time="0.0" classname="Testngpackage.LoginToActitime">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Testngpackage.LoginToActitime.login1(LoginToActitime.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
</testsuite> <!-- Test1 -->
